---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Deploy custom index.html
  ansible.builtin.template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
  notify:
    - Reload Nginx

- name: Start and enable Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Create SSL directory
  ansible.builtin.file:
    path: /etc/nginx/ssl
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Generate SSL key and certificate
  ansible.builtin.command: >
    openssl req -new -newkey rsa:2048 -days 365 -nodes -x509
    -keyout /etc/nginx/ssl/nginx-selfsigned.key
    -out /etc/nginx/ssl/nginx-selfsigned.crt
    -subj "/CN=maggio.com"
  args:
    creates: /etc/nginx/ssl/nginx-selfsigned.crt

- name: Configure SSL in Nginx
  ansible.builtin.template:
    src: nginx-ssl.conf.j2
    dest: /etc/nginx/conf.d/ssl.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload Nginx

- name: Deploy Nginx status configuration
  ansible.builtin.template:
    src: status.conf.j2
    dest: /etc/nginx/conf.d/status.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload Nginx

- name: Validate Nginx configuration
  ansible.builtin.command: nginx -t
  register: nginx_config_test
  changed_when: false
  failed_when: nginx_config_test.rc != 0
